### PR TITLE
Updated logo

### PR DESCRIPTION
**Pull request by abass**
Hey @clarkbk, thanks for doing the work to make this Chrome extension. Understandable that is has since been abandoned but figured I could give it a fresh coat of paint by updating the logos with HQ versions of their new logo.

Cheers!

### CODE REVIEW

**Comment by abass** [comment]
Hey @clarkbk, thanks for doing the work to make this Chrome extension. Understandable that is has since been abandoned but figured I could give it a fresh coat of paint by updating the logos with HQ versions of their new logo.

Cheers!

**Comment by clarkbk** [comment]
Hey @abass thanks for contributing and apologies for the slow reply. I very quickly checked out your PR locally. Seems legit. Merging and will update the extension in the Chrome web store shortly.

**Comment by clarkbk** [comment]
Update: Changes are pushed to the Chrome store. 👍

**Comment by abass** [comment]
Excellent! Thanks so much @clarkbk - Looks great!

**Pull request merged**
